# Done to increase the memory available to gradle and improve build times.
org.gradle.jvmargs=-Xmx4G
name=bbor
buildVersion=2.7
# leave a space to reduce merge conflicts on version change
minecraft_version=1.21.5
yarn_mappings=1.21.5+build.1
loader_version=0.16.14
loom_version=1.10-SNAPSHOT

# Fabric API
fabric_version=0.125.3+1.21.5

modmenu_version=13.0.3
