# Done to increase the memory available to gradle and improve build times.
org.gradle.jvmargs=-Xmx4G
name=bbor
buildVersion=2.6
# leave a space to reduce merge conflicts on version change
minecraft_version=1.21.4
yarn_mappings=1.21.4+build.8
loader_version=0.16.10

#Fabric api
fabric_version=0.115.1+1.21.4

modmenu_version=13.0.1
